[DOPS-2696]: update clippy workflow
sora-xor/sora2-parachain pull request #124
Opened 2023-08-21 17:16 UTC by f33r0

# Task

[DOPS-2696] update clippy workflow

## Changes

1. Added clippy workflow

## Author

Signed-off-by: name <zaporozhets@soramitsu.co.jp>

[DOPS-2696]: https://soramitsu.atlassian.net/browse/DOPS-2696

2023-08-23 06:24 UTC, wpi86 approved these changes

2023-08-23 06:25 UTC, wpi86 requested changes

2023-08-23 06:25 UTC, wpi86 commented on Jenkinsfile
>        codeCoverage: false,
why?

2023-08-25 07:00 UTC, Cre-eD approved these changes

2023-08-25 07:17 UTC, f33r0 commented on Jenkinsfile
>        codeCoverage: false,
is not implemented

2023-08-25 07:36 UTC, wpi86 approved these changes

2023-08-28 06:10 UTC, f33r0 commented
@N1ghtStorm  will be merged when the clippy branch is merged

2023-08-31 08:32 UTC, merged