Parachain governance
sora-xor/sora2-parachain pull request #142
Opened 2023-09-11 10:53 UTC by N1ghtStorm

2023-09-21 00:27 UTC, vovac12 requested changes

2023-09-21 00:27 UTC, vovac12 commented on parachain-common/src/weights.rs
> +const MAXIMUM_BLOCK_WEIGHT: Weight =
We already have this types in runtime/src/lib.rs. And also 2 secs is too much for parachain, it's usually 0.5sec AFAIK

2023-09-21 00:27 UTC, vovac12 commented on runtime/src/impls.rs
> +impl pallet_democracy::WeightInfo for DemocracyWeightInfo {
I think this impl can be removed here and in mainnet

2023-09-21 12:07 UTC, N1ghtStorm commented on parachain-common/src/weights.rs
> +const MAXIMUM_BLOCK_WEIGHT: Weight =
changed to default MAXIMUM_BLOCK_WEIGHT on the parachain

2023-09-21 12:08 UTC, N1ghtStorm commented on runtime/src/impls.rs
> +impl pallet_democracy::WeightInfo for DemocracyWeightInfo {
done

2023-09-22 15:27 UTC, vovac12 approved these changes

2023-09-22 15:27 UTC, vovac12 approved these changes

2023-09-25 00:14 UTC, merged