[duty]: update glibc
sora-xor/sora2-parachain pull request #220
Opened 2024-08-01 14:47 UTC by f33r0

1. updated debian
2. updated env image
3. updated llvm-tools

2024-08-02 05:12 UTC, wpi86 requested changes

2024-08-02 05:12 UTC, wpi86 commented on Jenkinsfile
> +@Library('jenkins-library@feature/dops-3304-update-rustlib') _
don't forget to revert

2024-08-19 05:13 UTC, C4tWithShell approved these changes

2024-08-19 06:00 UTC, alexkg approved these changes

2024-08-19 06:04 UTC, wpi86 approved these changes

2024-08-19 06:06 UTC, RamilMus approved these changes

2024-08-19 06:48 UTC, merged