Feature/test rust lib
sora-xor/sora2-parachain pull request #98
Opened 2023-05-31 14:45 UTC by f33r0

2023-06-16 05:45 UTC, wpi86 requested changes

2023-06-16 05:45 UTC, wpi86 commented on Jenkinsfile
> +      codeCoverage: false,
Why?

2023-06-16 05:45 UTC, wpi86 commented on Jenkinsfile
> +      staticScanner: false,
Why?

2023-06-16 05:45 UTC, wpi86 commented on Jenkinsfile
> +@Library('jenkins-library@feature/dops-2395/rust_library') _
```suggestion
@Library('jenkins-library') _
```

2023-06-16 05:46 UTC, f33r0 commented on Jenkinsfile
> +      staticScanner: false,
only for substrate

2023-06-16 05:47 UTC, f33r0 commented on Jenkinsfile
> +      codeCoverage: false,
only for substrate

2023-06-16 05:47 UTC, f33r0 commented on Jenkinsfile
> +@Library('jenkins-library@feature/dops-2395/rust_library') _
demo

2023-06-16 05:52 UTC, wpi86 approved these changes

2023-06-16 06:32 UTC, C4tWithShell approved these changes

2023-06-16 06:40 UTC, alexkg approved these changes

2023-07-04 05:58 UTC, wpi86 approved these changes

2023-07-05 05:45 UTC, wpi86 approved these changes

2023-07-06 11:10 UTC, Cre-eD commented on Jenkinsfile
> +      disableSecretScanner: false,
it's also must be by default

2023-07-06 11:10 UTC, Cre-eD commented on Jenkinsfile
> +      dockerImageTags: ['develop': 'dev', 'master': 'latest'],
it's also must be by default

2023-07-06 11:11 UTC, Cre-eD commented on Jenkinsfile
> +      secretScannerExclusion: '.*Cargo.toml\$|.*pr.sh\$',
it's also must be by default

2023-07-06 11:12 UTC, Cre-eD commented on Jenkinsfile
> +      codeCoverage: false,
we need to enable it but make sure it won't break CI

2023-07-06 11:12 UTC, Cre-eD commented on Jenkinsfile
> +      assignReviewers: true,
it's also must be by default

2023-07-06 11:13 UTC, Cre-eD commented on Jenkinsfile
> +      prStatusNotif: true
it's also must be by default

2023-07-10 05:41 UTC, wpi86 approved these changes

2023-07-14 08:21 UTC, Cre-eD approved these changes

2023-07-26 09:35 UTC, baotn166 approved these changes

2023-07-26 11:59 UTC, merged